### ISSUE TITLE
google-chrome-stable Gtk-WARNING **: 06:39:28.474: cannot open display: :0

### ISSUE THREAD

**Issue by jcleng** [fredx181/bionicdog#1]
hi,run google-chrome-stable and cannot open display,screenfetch this:
root@live64
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-22-generic
Shell: bash 4.4.19
WM: OpenBox
WM Theme: Bear2
GTK Theme: Greybird [GTK2/3]
Font: 文泉驿点阵正黑 Bold 10
CPU: Intel Celeron CPU G530 @ 2.4GHz
GPU: NVC1
RAM: 924MiB / 1976MiB
log this:
root@live64:/usr/share/fonts# su puppy
puppy@live64:/usr/share/fonts$ google-chrome-stable

(google-chrome-stable:16539): Gdk-WARNING **: 06:36:45.071: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
No protocol specified

(google-chrome-stable:16539): Gtk-WARNING **: 06:36:45.091: cannot open display: :0
puppy@live64:/usr/share/fonts$ google-chrome-stable

(google-chrome-stable:17943): Gdk-WARNING **: 06:39:28.473: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
No protocol specified

(google-chrome-stable:17943): Gtk-WARNING **: 06:39:28.474: cannot open display: :0

**Comment by fredx181** [comment]
When running `xhost +local:puppy` first it works for me, actually I use this script:  
```
#!/bin/sh

xhost +local:puppy

su puppy -c "/usr/bin/google-chrome-stable "$@" --user-data-dir=/home/puppy/chrome/user --disk-cache-dir=/home/puppy/chrome/cache --disk-cache-size=10000000 --media-cache-size=10000000 "$@""

```  
Fred
